import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Next13NProgress } from "nextjs13-progress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">

            <body className={inter.className}>
                <Next13NProgress 
                    color="#f1f5f9" 
                    startPosition={0.3} 
                    stopDelayMs={200} 
                    height={3} 
                    showOnShallow={true} 
                    options={{ 
                        // showSpinner : true
                     }}
                />
                <AntdRegistry>
                    {children}
                </AntdRegistry>
            </body>

        </html>
    );
}
